title: A Title
author: 
  - Aaron Gullickson, *University of Oregon*
  - Fave Coauthor, *Some University*
abstract: This is a test abstract
thanks: The corresponding author can be reached at aarong@uoregon.edu. All code and data for this project are available at ...
bibliography: references.bib  


